apiVersion: v1
kind: ConfigMap
metadata:
  name: shoppingclient-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_HTTP_PORTS: "8002"
  APIConfig__BaseAddress: "http://shoppingapi-service:8000"