apiVersion: v1
kind: ConfigMap
metadata:
  name: shoppingapi-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_HTTP_PORTS: "8000"
  DatabaseSettings__ConnectionString: "mongodb://mongodb-service:27017"